# Generated by Django 5.2.3 on 2025-07-21 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Clubes'},
        ),
        migrations.AlterField(
            model_name='club',
            name='foundation_year',
            field=models.DateField(blank=True, null=True, verbose_name='Año de Fundación'),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Clubs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='club',
            name='titles_won',
            field=models.TextField(default=0, verbose_name='Títulos Ganados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
